services:
  mp-charts:
    image: registry.gitlab.com/moodychurch/mp-charts:latest
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - caddy_network
    volumes:
      - data:/app/data

networks:
  caddy_network:
    external: true

volumes:
  data:
