import { z } from 'zod';

export const BackgroundChecksSchema = z.object({
  Background_Check_ID: z.number().int(),
  Contact_ID: z.number().int(),
  Requesting_Ministry: z.number().int().nullable(),
  Background_Check_Submitted: z.string().datetime().nullable(),
  Background_Check_Returned: z.string().datetime().nullable(),
  All_Clear: z.boolean().nullable(),
  Notes: z.string().max(500).nullable(),
  Theft: z.boolean().nullable(),
  Drugs: z.boolean().nullable(),
  Sexual: z.boolean().nullable(),
  DUI: z.boolean().nullable(),
  Battery: z.boolean().nullable(),
  Traffic: z.boolean().nullable(),
  Other: z.boolean().nullable(),
  Background_Check_Started: z.string().datetime(),
  Reference_Number: z.string().max(50).nullable(),
  Report_Url: z.string().url().nullable(),
  Background_Check_Type_ID: z.number().int().nullable(),
  Background_Check_GUID: z.string().uuid(),
  First_Name: z.string().max(50).nullable(),
  Middle_Name: z.string().max(50).nullable(),
  Last_Name: z.string().max(50).nullable(),
  Maiden_Name: z.string().max(50).nullable(),
  Date_Of_Birth: z.string().datetime().nullable(),
  Gender: z.string().max(50).nullable(),
  Race: z.string().max(50).nullable(),
  Address_Line_1: z.string().max(128).nullable(),
  City: z.string().max(50).nullable(),
  State: z.string().max(50).nullable(),
  Postal_Code: z.string().max(50).nullable(),
  Digital_Signature: z.string().max(128).nullable(),
  DL_Number: z.string().max(50).nullable(),
  Jurisdiction: z.string().max(128).nullable(),
  DL_State: z.string().max(50).nullable(),
  Background_Check_Expires: z.string().datetime().nullable(),
  Background_Check_Status_ID: z.number().int().nullable(),
  Status_Date: z.string().datetime().nullable(),
  IP_Address: z.string().max(45).nullable(),
});

export type BackgroundChecksInput = z.infer<typeof BackgroundChecksSchema>;
