import { z } from 'zod';

export const CongregationsSchema = z.object({
  Congregation_ID: z.number().int(),
  Congregation_Name: z.string().max(50),
  Description: z.string().max(255).nullable(),
  Start_Date: z.string().datetime(),
  End_Date: z.string().datetime().nullable(),
  Accounting_Company_ID: z.number().int(),
  Available_Online: z.boolean(),
  Location_ID: z.number().int().nullable(),
  Time_Zone: z.unknown(),
  Contact_ID: z.number().int(),
  Pastor: z.number().int(),
  Online_Sort_Order: z.number().int().nullable(),
  Front_Desk_SMS_Phone: z.string().nullable(),
  Plan_A_Visit_Template: z.number().int().nullable(),
  Plan_A_Visit_User: z.number().int().nullable(),
  Giving_URL: z.string().max(500).nullable(),
  Logo_URL: z.string().max(500).nullable(),
  Coming_Soon: z.boolean(),
  Giving_Image_URL: z.string().max(500).nullable(),
  JWT_Signing_Key: z.unknown().nullable(),
  Certifications_Provider: z.string().max(25).nullable(),
  Certifications_API_Key: z.unknown().nullable(),
  Certifications_API_Address: z.string().max(100).nullable(),
  Certification_Callback_Username: z.string().max(50).nullable(),
  Certification_Callback_Password: z.unknown().nullable(),
  Background_Check_Provider: z.string().max(25).nullable(),
  Background_Check_Username: z.string().max(50).nullable(),
  Background_Check_Password: z.unknown().nullable(),
  Background_Check_Callback_Username: z.string().max(50).nullable(),
  Background_Check_Callback_Password: z.unknown().nullable(),
  Event_Registration_Handoff_URL: z.string().url().nullable(),
  Vanco_Tenant: z.string().max(50).nullable(),
  Vanco_Giving_PCCT: z.string().max(50).nullable(),
  Vanco_Signing_Key: z.string().max(50).nullable(),
  Organization_Code: z.string().max(16).nullable(),
  Sacrament_Place_ID: z.number().int().nullable(),
  Dark_Mode_Logo_URL: z.string().max(500).nullable(),
  Site_Number: z.string().max(8).nullable(),
  App_ID: z.number().int().nullable(),
});

export type CongregationsInput = z.infer<typeof CongregationsSchema>;
