import { z } from 'zod';

export const ContactStagingSchema = z.object({
  Contact_Staging_ID: z.number().int(),
  Ignore: z.boolean(),
  Imported: z.boolean().nullable(),
  Finalized: z.boolean().nullable(),
  Display_Name: z.string().max(75),
  Existing_Contact_Record: z.number().int().nullable(),
  External_ID: z.string().max(50).nullable(),
  ExternalFamilyID: z.number().int().nullable(),
  Company: z.boolean(),
  Company_Name: z.string().max(50).nullable(),
  Prefix_ID: z.number().int().nullable(),
  First_Name: z.string().max(50).nullable(),
  Middle_Name: z.string().max(50).nullable(),
  Last_Name: z.string().max(50).nullable(),
  Suffix_ID: z.number().int().nullable(),
  Nickname: z.string().max(50).nullable(),
  Date_of_Birth: z.string().datetime().nullable(),
  Gender_ID: z.number().int().nullable(),
  Marital_Status_ID: z.number().int().nullable(),
  Contact_Status_ID: z.number().int(),
  Existing_Household_Record: z.number().int().nullable(),
  Household_Position_ID: z.number().int().nullable(),
  Existing_Participant_Record: z.number().int().nullable(),
  Participant_Start_Date: z.string().datetime().nullable(),
  Participant_Type_ID: z.number().int().nullable(),
  Participant_Notes: z.string().max(1000).nullable(),
  Existing_Donor_Record: z.number().int().nullable(),
  Email_Address: z.string().max(254).nullable(),
  Bulk_Email_Opt_Out: z.boolean(),
  Mobile_Phone: z.string().nullable(),
  Company_Phone: z.string().nullable(),
  Pager_Phone: z.string().nullable(),
  Fax_Phone: z.string().nullable(),
  Existing_User_Account: z.number().int().nullable(),
  Web_Page: z.string().url().nullable(),
  Anniversary_Date: z.string().datetime().nullable(),
  HS_Graduation_Year: z.number().int().nullable(),
  Home_Phone: z.string().nullable(),
  Congregation_ID: z.number().int().nullable(),
  Existing_Address_Record: z.number().int().nullable(),
  Address_Line_1: z.string().max(75).nullable(),
  Address_Line_2: z.string().max(75).nullable(),
  City: z.string().max(50).nullable(),
  "State/Region": z.string().max(50).nullable(),
  Postal_Code: z.string().max(15).nullable(),
  Foreign_Country: z.string().max(50).nullable(),
  ID_Card: z.string().max(50).nullable(),
  Date_of_Death: z.string().datetime().nullable(),
  _Contact_Setup_Date: z.string().datetime().nullable(),
});

export type ContactStagingInput = z.infer<typeof ContactStagingSchema>;
