import { z } from 'zod';

export const ContactsSchema = z.object({
  Contact_ID: z.number().int(),
  Company: z.boolean(),
  Company_Name: z.string().max(50).nullable(),
  Display_Name: z.string().max(125),
  Prefix_ID: z.number().int().nullable(),
  First_Name: z.string().max(50).nullable(),
  Middle_Name: z.string().max(50).nullable(),
  Last_Name: z.string().max(50).nullable(),
  Suffix_ID: z.number().int().nullable(),
  Nickname: z.string().max(50).nullable(),
  Date_of_Birth: z.string().datetime().nullable(),
  Gender_ID: z.number().int().nullable(),
  Marital_Status_ID: z.number().int().nullable(),
  Contact_Status_ID: z.number().int(),
  Household_ID: z.number().int().nullable(),
  Household_Position_ID: z.number().int().nullable(),
  Anniversary_Date: z.string().datetime().nullable(),
  Date_of_Death: z.string().datetime().nullable(),
  Participant_Record: z.number().int().nullable(),
  Donor_Record: z.number().int().nullable(),
  Email_Address: z.string().email().max(254).nullable(),
  Mobile_Phone: z.string().nullable(),
  Company_Phone: z.string().nullable(),
  Pager_Phone: z.string().nullable(),
  Fax_Phone: z.string().nullable(),
  Facebook_Account: z.string().max(50).nullable(),
  Twitter_Account: z.string().max(50).nullable(),
  Web_Page: z.string().url().nullable(),
  Industry_ID: z.number().int().nullable(),
  Occupation_ID: z.number().int().nullable(),
  Current_School: z.string().max(75).nullable(),
  HS_Graduation_Year: z.number().int().nullable(),
  Bulk_Email_Opt_Out: z.boolean(),
  Email_Unlisted: z.boolean(),
  Do_Not_Text: z.boolean(),
  Mobile_Phone_Unlisted: z.boolean(),
  Remove_From_Directory: z.boolean(),
  User_Account: z.number().int().nullable(),
  ID_Card: z.string().max(50).nullable(),
  Contact_GUID: z.string().uuid(),
  _Contact_Setup_Date: z.string().datetime(),
  Email_Verified: z.boolean(),
  Mobile_Phone_Verified: z.boolean(),
  Maiden_Name: z.string().max(50).nullable(),
  Primary_Language_ID: z.number().int().nullable(),
  Faith_Background_ID: z.number().int().nullable(),
  Texting_Opt_In_Type_ID: z.number().int(),
});

export type ContactsInput = z.infer<typeof ContactsSchema>;
