import { z } from 'zod';

export const EventsSchema = z.object({
  Event_ID: z.number().int(),
  Event_Title: z.string().max(75),
  Event_Type_ID: z.number().int(),
  Congregation_ID: z.number().int(),
  Location_ID: z.number().int().nullable(),
  Meeting_Instructions: z.string().max(4000).nullable(),
  Description: z.string().max(2000).nullable(),
  Program_ID: z.number().int(),
  Primary_Contact: z.number().int(),
  Participants_Expected: z.number().int().nullable(),
  Minutes_for_Setup: z.number().int(),
  Event_Start_Date: z.string().datetime(),
  Event_End_Date: z.string().datetime(),
  Minutes_for_Cleanup: z.number().int(),
  Cancelled: z.boolean(),
  _Approved: z.boolean().nullable(),
  Visibility_Level_ID: z.number().int(),
  Featured_On_Calendar: z.boolean(),
  Online_Registration_Product: z.number().int().nullable(),
  Registration_Form: z.number().int().nullable(),
  Registration_Start: z.string().datetime().nullable(),
  Registration_End: z.string().datetime().nullable(),
  Registration_Active: z.boolean(),
  Register_Into_Series: z.boolean(),
  External_Registration_URL: z.string().url().nullable(),
  _Web_Approved: z.boolean().nullable(),
  Force_Login: z.boolean(),
  "Allow_Check-in": z.boolean(),
  Ignore_Program_Groups: z.boolean(),
  Prohibit_Guests: z.boolean(),
  Search_Results: z.number().int(),
  "Early_Check-in_Period": z.number().int().nullable(),
  "Late_Check-in_Period": z.number().int().nullable(),
  Registrant_Message: z.number().int().nullable(),
  Days_Out_to_Remind: z.number().int().nullable(),
  Optional_Reminder_Message: z.number().int().nullable(),
  Attendee_Message: z.number().int().nullable(),
  Send_To_Heads: z.boolean(),
  Parent_Event_ID: z.number().int().nullable(),
  Priority_ID: z.number().int().nullable(),
  On_Connection_Card: z.boolean(),
  On_Donation_Batch_Tool: z.boolean(),
  Project_Code: z.string().max(15).nullable(),
  Online_Meeting_Link: z.string().max(2083).nullable(),
  Read_More_URL: z.string().max(1000).nullable(),
  Allow_Self_Checkin: z.boolean(),
  Minor_Registration: z.boolean(),
  Allow_Email: z.boolean(),
  Show_Building_Room_Info: z.boolean(),
  Allow_QR_Check_In: z.boolean(),
  QR_Redirect_Url: z.string().max(300).nullable(),
  Allow_Fastpass: z.boolean(),
});

export type EventsInput = z.infer<typeof EventsSchema>;
