import { z } from 'zod';

export const GroupsSchema = z.object({
  Group_ID: z.number().int(),
  Group_Name: z.string().max(75),
  Group_Type_ID: z.number().int(),
  Ministry_ID: z.number().int(),
  Congregation_ID: z.number().int(),
  Primary_Contact: z.number().int(),
  Description: z.string().max(2000).nullable(),
  Start_Date: z.string().datetime(),
  End_Date: z.string().datetime().nullable(),
  Target_Size: z.number().int().nullable(),
  Parent_Group: z.number().int().nullable(),
  Priority_ID: z.number().int().nullable(),
  Offsite_Meeting_Address: z.number().int().nullable(),
  Group_Is_Full: z.boolean(),
  Available_Online: z.boolean(),
  Meets_Online: z.boolean(),
  Life_Stage_ID: z.number().int().nullable(),
  Group_Focus_ID: z.number().int().nullable(),
  Meeting_Time: z.string().nullable(),
  Meeting_Day_ID: z.number().int().nullable(),
  Meeting_Frequency_ID: z.number().int().nullable(),
  Meeting_Duration_ID: z.number().int().nullable(),
  Required_Book: z.number().int().nullable(),
  Descended_From: z.number().int().nullable(),
  Reason_Ended: z.number().int().nullable(),
  _Last_Attendance_Posted: z.string().datetime().nullable(),
  _Last_Group_Member_Changed: z.string().datetime().nullable(),
  "Secure_Check-in": z.boolean(),
  Suppress_Nametag: z.boolean(),
  Suppress_Care_Note: z.boolean(),
  On_Classroom_Manager: z.boolean(),
  Promote_to_Group: z.number().int().nullable(),
  Age_in_Months_to_Promote: z.number().int().nullable(),
  Promote_Weekly: z.boolean(),
  Promotion_Date: z.string().datetime().nullable(),
  Promote_Participants_Only: z.boolean(),
  Send_Attendance_Notification: z.boolean(),
  Send_Service_Notification: z.boolean(),
  Enable_Discussion: z.boolean(),
  SMS_Number: z.number().int().nullable(),
  Default_Meeting_Room: z.number().int().nullable(),
  Create_Next_Meeting: z.boolean(),
  Next_Scheduled_Meeting: z.string().datetime().nullable(),
  Available_On_App: z.boolean().nullable(),
});

export type GroupsInput = z.infer<typeof GroupsSchema>;
