import { z } from 'zod';

export const ParticipantMilestonesSchema = z.object({
  Participant_Milestone_ID: z.number().int(),
  Participant_ID: z.number().int(),
  Milestone_ID: z.number().int(),
  Program_ID: z.number().int(),
  Date_Accomplished: z.string().datetime().nullable(),
  Event_ID: z.number().int().nullable(),
  Witness: z.number().int().nullable(),
  At_Prior_Church: z.boolean(),
  Notes: z.string().max(2000).nullable(),
  Followed_Up: z.boolean(),
  Discontinue_Journey: z.boolean(),
  Performed_By: z.string().max(150).nullable(),
  Place: z.string().max(255).nullable(),
  Sacramental_Name: z.string().max(150).nullable(),
  Received: z.boolean(),
  Registry_Volume: z.number().int().nullable(),
  Registry_Page: z.number().int().nullable(),
  Registry_Number: z.number().int().nullable(),
  Witness_1: z.string().max(254).nullable(),
  Witness_2: z.string().max(254).nullable(),
  Person_1: z.string().max(254).nullable(),
  Person_2: z.string().max(254).nullable(),
  Mother_Name: z.string().max(254).nullable(),
  Mother_Maiden_Name: z.string().max(254).nullable(),
  Mother_Religion: z.string().max(254).nullable(),
  Father_Name: z.string().max(254).nullable(),
  Father_Religion: z.string().max(254).nullable(),
  Spouse_Name: z.string().max(150).nullable(),
  Spouse_Baptism: z.string().max(150).nullable(),
  Spouse_Baptism_Church: z.string().max(150).nullable(),
  Spouse_Baptism_Street: z.string().max(150).nullable(),
  Spouse_Baptism_City: z.string().max(150).nullable(),
  Spouse_Baptism_State: z.string().max(75).nullable(),
  Spouse_Baptism_Zip: z.string().max(75).nullable(),
  Spouse_Parent_1: z.string().max(150).nullable(),
  Spouse_Parent_2: z.string().max(150).nullable(),
});

export type ParticipantMilestonesInput = z.infer<typeof ParticipantMilestonesSchema>;
